all.js: FUSE01B.js helper.js vector.js point.js segment.js ball.js glue.js goal.js score.js life.js main.js
	cat FUSE01B.js helper.js vector.js point.js segment.js ball.js glue.js goal.js score.js life.js main.js > all.js
